BACKUPBASEPATH = '/examplefolder/'
MIGRATEBASHSCRIPTPATH = '/path/migratescript.sh'
MIGARTEJSSCRIPTBASEPATH = '/path/folderStoringJS/'
SECRET_KEY = 'secret key here'
DEBUG = False
HOST = '127.0.0.1'
PORT = 8000
USERNAME = ''
PASSWORD = ''
